### ISSUE TITLE
Error 405 after logging in (Due to user agent set in fetch_news_feed_

### ISSUE THREAD

**Issue by ObscureStrength** [instagrambot/instagram-terminal-news-feed#19]
I bump into `ERROR: got 405 when fetching!` upon successfully logging in from macOS terminal. I get the email from Instagram that I'm logging in from a new device so I'm certain this is not an authentication issue. Curious if anyone knows why this occurs

**Comment by billcccheng** [comment]
Thanks for issue. Fixed it :)
