### ISSUE TITLE
Not rendering in Window's CLI.

### ISSUE THREAD

**Issue by Broken-Admin** [instagrambot/instagram-terminal-news-feed#2]
![capture286](https://user-images.githubusercontent.com/28983778/37998253-84d9c064-31e3-11e8-9902-136200713050.PNG)
Terminal Capture, improperly rendering for one or more reasons.

**Comment by billcccheng** [comment]
Hmm... I tried on my Windows machine and it's working. Any more logs so we can actually trace what's going on?

**Comment by Broken-Admin** [comment]
I may be currently lacking the unicode, other libraries seem to not be working for me too.

**Comment by billcccheng** [comment]
Try following this repo: https://github.com/adoxa/ansicon to install the necessary stuffs to render the ascii image in windows.

Let me know if you have any more problem!

**Comment by Broken-Admin** [comment]
I try to use it on a new system I bought recently.
[Didn't work.](https://i.imgur.com/p2RlCwR.png)
